//! Native CoreML model layer for Silero VAD — the FluidInference unified
//! 256 ms artifact (`silero-vad-unified-256ms-v6.2.1`), run through the
//! [`coremlit`] runtime instead of ONNX Runtime.
//!
//! Design spec:
//! `docs/superpowers/specs/2026-07-18-vadkit-design.md` (§4 model layer, §5
//! adoption, §6 gates). Plan:
//! `docs/superpowers/plans/2026-07-18-vadkit-plan.md`.
//!
//! macOS only (built on [`coremlit`]).
//!
//! # Scope: model layer only, no detection logic
//!
//! This crate wraps ONE stateful CoreML graph — 256 ms (4096-sample) chunks
//! of 16 kHz mono audio in, one speech probability per chunk out, with the
//! recurrent LSTM state carried across chunks — and the 64-sample context
//! stitching that graph expects (the FluidAudio `VadManager` semantics,
//! `FluidAudio/Sources/FluidAudio/VAD/VadManager.swift:21-26`). It authors
//! **zero** speech-detection or streaming-segmentation logic: that lives, and
//! stays single-homed, in the published `silero` crate behind its backend
//! seam (spec §2-§3). [`CoreMlBackend`] implements that seam over CoreML and
//! [`detect_speech`] plus the re-exported [`silero`] detector surface
//! ([`SpeechOptions`], [`SpeechSegment`], [`SpeechSegmenter`],
//! [`detect_speech_with`]) wire it up (spec §4) — so a vadkit consumer gets the
//! full offline + streaming detection API with zero segmentation logic
//! authored here. The `src/` grep gate in `tests/reexport.rs` pins that
//! single-home invariant.
//!
//! # Oracle
//!
//! The model layer is pinned against the real FluidAudio Swift `VadManager`:
//! committed per-chunk probability traces (`tests/parity_swift.rs`,
//! `tests/fixtures/golden_swift/`) generated by
//! `tests/swift/regen_goldens.sh`, plus the exact I/O contract and per-file
//! SHA-256 pins in `tests/model_io.rs`, and the fp16-guard sweep in
//! `coremlit`'s `tests/fp16_guards.rs` (vendor `vadkit`; the graph is
//! fp16-clean — see that file's `accepts_vadkits_stft_sqrt_guard`).

pub mod backend;
pub mod error;
pub mod model;

pub use backend::{CoreMlBackend, detect_speech};
pub use error::{InferError, ModelError};
pub use model::{
  CHUNK_SAMPLES, CONTEXT_SAMPLES, MODEL_INPUT_SAMPLES, STATE_SIZE, VadModel, VadModelOptions,
  VadState,
};

// The silero detector surface, re-exported unchanged and wired (via
// [`CoreMlBackend`] / [`detect_speech`]) to run over the CoreML backend. vadkit
// adds NO detection logic (spec §2-§4); these are silero's own types. `Error`
// / `Result` are silero's detector error (into which the model layer's
// [`InferError`] bridges through [`silero::Error::Backend`]), distinct from the
// model-layer [`ModelError`] / [`InferError`] above.
pub use silero::{
  Error, Result, SampleRate, SpeechDetector, SpeechOptions, SpeechSegment, SpeechSegmenter,
  VadBackend, detect_speech_with,
};
