//! Native CoreML model layer for Silero VAD — the FluidInference unified
//! 256 ms artifact (`silero-vad-unified-256ms-v6.2.1`), run through the
//! [`coremlit`] runtime instead of ONNX Runtime.
//!
//! Design spec:
//! `docs/superpowers/specs/2026-07-18-vadkit-design.md` (§4 model layer, §5
//! adoption, §6 gates). Plan:
//! `docs/superpowers/plans/2026-07-18-vadkit-plan.md`.
//!
//! macOS only (built on [`coremlit`]).
//!
//! # Scope: model layer only, no detection logic
//!
//! This crate wraps ONE stateful CoreML graph — 256 ms (4096-sample) chunks
//! of 16 kHz mono audio in, one speech probability per chunk out, with the
//! recurrent LSTM state carried across chunks — and the 64-sample context
//! stitching that graph expects (the FluidAudio `VadManager` semantics,
//! `FluidAudio/Sources/FluidAudio/VAD/VadManager.swift:21-26`). It authors
//! **zero** speech-detection or streaming-segmentation logic: that lives, and
//! stays single-homed, in the published `silero` crate behind its backend
//! seam (spec §2-§3). vadkit implements that seam over CoreML and re-exports
//! silero's detector surface (spec §4) — the seam impl and re-export are a
//! later task (T5); this module is the model layer alone (T2/T3).
//!
//! # Oracle
//!
//! The model layer is pinned against the real FluidAudio Swift `VadManager`:
//! committed per-chunk probability traces (`tests/parity_swift.rs`,
//! `tests/fixtures/golden_swift/`) generated by
//! `tests/swift/regen_goldens.sh`, plus the exact I/O contract and per-file
//! SHA-256 pins in `tests/model_io.rs`, and the fp16-guard sweep in
//! `coremlit`'s `tests/fp16_guards.rs` (vendor `vadkit`; the graph is
//! fp16-clean — see that file's `accepts_vadkits_stft_sqrt_guard`).

pub mod error;
pub mod model;

pub use error::{InferError, ModelError};
pub use model::{
  CHUNK_SAMPLES, CONTEXT_SAMPLES, MODEL_INPUT_SAMPLES, STATE_SIZE, VadModel, VadModelOptions,
  VadState,
};
